raw_dir_a = '../eye_tracker/eye_tracking-selected/suffrage_a/'
raw_dir_b = '../eye_tracker/eye_tracking-selected/suffrage_b/'
data_dir = '../pipeline-data/'
frame_images_dir = 'frame-images'
metadata_file = 'metadata.json'
images_ready_for_ocr = 'resized-images'